(project):
    (profile_sources):
        - ./pretty_names.yaml
        - ./signal.yaml
        - ./agent.yaml
    (profiles):
        (default):
            processors: 20    # null for all
            trials: 5   # Number of independent random-seeded trials to run for exp_runners
            tamu_launcher: False    # Texas A&M University has a custom process launcher on HPRC clusters
            controlled_signals: null    # List of signals to control, null for all

            log_level: INFO
            log_console: False
            compress_results: False
            delete_logs: False   # Only when compress_results is true, logs can use A LOT of space
            config_builder: False    # Dry-run to generate config/hashes before running full trials so they can be named

            action_set: Phase
            episodes: 100
            converged: null   # Number of episodes to wait for convergence, null to disable, at least 'episodes' to run
            log_dir: results
            gui: False
            libsumo: True

            load_sim: null
            save_frequency: 20
            load_model: null    # TODO reinstate loading
            load_replay: True   # If a replay exists, load it and continue training - only when load_model set

            training: True
            testing: 0   # TODO Number of episodes to run after training with exploration turned off

            flow: 1.0   # Scales original traffic demand, 1.0 = original
            curriculum: null
            step_off: 0

            learning_rate: 1e-3
            gpu: 0              # TODO, not sure if this is still implemented, use CUDA_VISIBLE_DEVCICES env var

            max_distance: 200
            step_length: 5
            yellow_length: 3
            clearance_length: 2
            step_ratio: 1

            run_peak: null  # One of [peak, low, null]  only applies to saltlake

            flat_state: True
            auto_scale: False    # Convenience method to avoid manually scaling obs/rew

            # Optuna settings
            optuna_objective: null  # If specified will run an optuna search
            optuna_trials: 1000     # Unlimited if null

            # Result plotting settings
            error_bars: True
            smoothing: 5   # Null for none
            xml_metrics: ['timeLoss', 'duration', 'waitingTime']
            csv_metrics: ['rewards', 'max_queues', 'queue_lengths', 'vehicles', 'phase_length']




        # Map configurations below

        saltlake2_stateXuniversity:
            network: saltlake2_stateXuniversity.net.xml
            route: saltlake2_stateXuniversity.flo.xml

            start_time: 0
            end_time: 86400

            #Peak volume: 6852, Low volume: 281
            peak_date: 2023-6-27
            peak_hour: 61200
            low_hour: 7200

            start_date: 2023-1-1
            end_date: 2024-1-1  # Only used when scanning csv's for peak date

            # Missing data intervals, will be skipped over
            missing_start: ['2023-02-09 11:20']
            missing_end: ['2023-02-13 09:05']

        saltlake1A_stateXuniversity:
            network: saltlake1A_stateXuniversity.net.xml
            route: saltlake1A_stateXuniversity.flo.xml

            start_time: 0
            end_time: 86400

            #Peak volume: 6852, Low volume: 281
            peak_date: 2023-6-27
            peak_hour: 61200
            low_hour: 7200

            start_date: 2023-1-1
            end_date: 2024-1-1  # Only used when scanning csv's for peak date

            # Missing data intervals, will be skipped over
            missing_start: [ '2023-02-09 11:20' ]
            missing_end: [ '2023-02-13 09:05' ]

        saltlake1B_stateXuniversity:
            network: saltlake1B_stateXuniversity.net.xml
            route: saltlake1B_stateXuniversity.flo.xml

            start_time: 0
            end_time: 86400

            #Peak volume: 6852, Low volume: 281
            peak_date: 2023-6-27
            peak_hour: 61200
            low_hour: 7200

            start_date: 2023-1-1
            end_date: 2024-1-1  # Only used when scanning csv's for peak date

            # Missing data intervals, will be skipped over
            missing_start: [ '2023-02-09 11:20' ]
            missing_end: [ '2023-02-13 09:05' ]

        saltlake2_400sX200w:     
            network: saltlake2_400sX200w.net.xml
            route: saltlake2_400sX200w.flo.xml

            start_time: 0
            end_time: 86400

            peak_date: 2023-2-3
            peak_hour: 64800
            low_hour: 10800

            start_date: 2023-1-1
            end_date: 2024-1-1

            missing_start: []
            missing_end: []

        saltlake1A_400sX200w:
            network: saltlake1A_400sX200w.net.xml
            route: saltlake1A_400sX200w.flo.xml

            start_time: 0
            end_time: 86400

            peak_date: 2023-2-3
            peak_hour: 64800
            low_hour: 10800

            start_date: 2023-1-1
            end_date: 2024-1-1

            missing_start: [ ]
            missing_end: [ ]

        saltlake1B_400sX200w:
            network: saltlake1B_400sX200w.net.xml
            route: saltlake1B_400sX200w.flo.xml

            start_time: 0
            end_time: 86400

            peak_date: 2023-2-3
            peak_hour: 64800
            low_hour: 10800

            start_date: 2023-1-1
            end_date: 2024-1-1

            missing_start: [ ]
            missing_end: [ ]

        grid1x1:
            network: grid1x1.net.xml
            route: grid1x1.flo.xml
            start_time: 0    
            end_time: 3600
            
        grid1x2:     
            network: grid1x2.net.xml
            route: grid1x2.flo.xml
            start_time: 0    
            end_time: 3600
            
        grid4x4:     
            network: grid4x4.net.xml
            route: grid4x4
            start_time: 0    
            end_time: 3600
            
        arterial4x4:     
            network: arterial4x4.net.xml
            route: arterial4x4
            start_time: 0    
            end_time: 3600
            
        ingolstadt1:     
            network: ingolstadt1.net.xml
            route: ingolstadt1.rou.xml
            start_time: 57600    
            end_time: 61200
            
        ingolstadt7:     
            network: ingolstadt7.net.xml
            route: ingolstadt7.rou.xml
            start_time: 57600    
            end_time: 61200
            
        ingolstadt21:     
            network: ingolstadt21.net.xml
            route: ingolstadt21.rou.xml
            start_time: 57600    
            end_time: 61200
            
        cologne1:     
            network: cologne1.net.xml
            route: cologne1.rou.xml
            start_time: 25200    
            end_time: 28800
            
        cologne3:     
            network: cologne3.net.xml
            route: cologne3.rou.xml
            start_time: 25200    
            end_time: 28800
            
        cologne8:     
            network: cologne8.net.xml
            route: cologne8.rou.xml
            start_time: 25200    
            end_time: 28800
